"""Generate the Stage 2 clean-up tables for the report.

Writes one markdown file holding the full ordered rule table and ten
before/after examples drawn from the cleaned corpus.  The rule table comes
from ``describe_rules()``, so the report cannot drift away from the code.

    python -m tools.make_examples

Output: docs/report/preprocess_examples.md
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.extraction.clean_text import PLACEHOLDERS, SEED, describe_rules, clean

from src.paths import ROOT, SE_DIR
OUT = ROOT / "docs/report/preprocess_examples.md"

N_EXAMPLES = 10
N_WITH_PLACEHOLDER = 6  # of the ten, how many must exercise a placeholder rule
MAX_CHARS = 170


def _cell(text: str) -> str:
    """Escape a string for a markdown table cell."""
    text = " ".join(str(text).split())
    if len(text) > MAX_CHARS:
        text = text[: MAX_CHARS - 1].rstrip() + "…"
    return text.replace("|", "\\|")


def _pick(df: pd.DataFrame) -> pd.DataFrame:
    """Ten rows, weighted toward ones where the placeholder rules actually fire."""
    out = df.assign(after=df["text"].map(clean))
    fires = out["after"].str.contains("|".join(PLACEHOLDERS), regex=True)

    interesting = out[fires].sample(
        n=min(N_WITH_PLACEHOLDER, int(fires.sum())), random_state=SEED
    )
    plain = out[~fires].sample(
        n=min(N_EXAMPLES - len(interesting), int((~fires).sum())), random_state=SEED
    )
    return pd.concat([interesting, plain])


def _code(value: str) -> str:
    """Inline-code a regex for a markdown table cell.

    Pipes would end the cell, and a pattern containing a backtick needs a
    double-backtick fence with padding spaces to survive.
    """
    if value == "-":
        return "-"
    escaped = value.replace("|", "\\|")
    fence = "``" if "`" in escaped else "`"
    pad = " " if "`" in escaped else ""
    return f"{fence}{pad}{escaped}{pad}{fence}"


def _rule_table() -> list[str]:
    lines = [
        "| # | scope | rule | pattern | replacement |",
        "|---|---|---|---|---|",
    ]
    for step, scope, name, pattern, repl in describe_rules():
        lines.append(
            f"| {step} | {scope} | {name} | {_code(pattern)} | {_code(repl)} |"
        )
    return lines


def main() -> None:
    lines = [
        "# Preprocessing rules and examples",
        "",
        "Generated by `python -m tools.make_examples`. Do not edit by hand.",
        "",
    ]

    clean_csv = SE_DIR / "clean.csv"
    lines += ["### Rules, in application order", ""]
    lines += _rule_table()
    lines += ["", "### Before / after", ""]

    if not clean_csv.exists():
        lines += [
            f"_`{clean_csv.relative_to(ROOT)}` not found "
            f"-- run `python -m src.extraction.build_se` first._",
            "",
        ]
    else:
        df = pd.read_csv(clean_csv, sep=";")
        picked = _pick(df)
        lines += ["| id | before | after |", "|---|---|---|"]
        lines += [
            f"| {row.id} | {_cell(row.text)} | {_cell(row.after)} |"
            for row in picked.itertuples()
        ]
        lines += [""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
